# Download and install EPEL for CentOS7/RHEL7
- name: Download EPEL Repo - CentOS7/RHEL7
  get_url: url={{ epelRepository }} dest=/tmp/epel-release-7-5.noarch.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
 
- name: Install EPEL Repo - CentOS7/RHEL7
  command: rpm -ivh /tmp/epel-release-7-5.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install fpint,iksemel
  yum: name={{ item }} enablerepo=epel state=latest
  with_items:
    - fping
    - iksemel